name: app_brick_generator

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install Dependencies
        run: dart pub get -C ./generator

      - name: Generate Template
        run: dart ./generator/main.dart

      - name: Config Git
        run: |
          git config user.name Jeevan
          git config user.email Jeevan@G1Joshi.dev
          git add .
          git commit -m "app-brick-generator"
          git push
